<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Add PROWARE's internal receipt number and rename the
     * existing reference field as a supplier reference.
     */
    public function up(): void
    {
        Schema::table(
            'stock_movements',
            function (Blueprint $table): void {
                /*
                 * Internal tracking number generated by PROWARE.
                 *
                 * It is temporarily nullable because existing
                 * stock movements were created before automatic
                 * receipt numbers were introduced.
                 */
                $table->string(
                    'receipt_number',
                    30,
                )
                    ->nullable()
                    ->unique(
                        'stock_movements_receipt_number_unique',
                    )
                    ->after('id');

                /*
                 * The original reference_number column already
                 * stores external delivery or supplier documents.
                 *
                 * Rename it so its purpose is unambiguous.
                 */
                $table->renameColumn(
                    'reference_number',
                    'supplier_reference_number',
                );
            },
        );
    }

    /**
     * Restore the previous stock movement structure.
     */
    public function down(): void
    {
        Schema::table(
            'stock_movements',
            function (Blueprint $table): void {
                $table->renameColumn(
                    'supplier_reference_number',
                    'reference_number',
                );

                $table->dropUnique(
                    'stock_movements_receipt_number_unique',
                );

                $table->dropColumn(
                    'receipt_number',
                );
            },
        );
    }
};
